[build]
  command = "npm run build"
  publish = "dist"

# Proxy de /api → backend real
[[redirects]]
  from = "/api/*"
  to = "https://xkcd.com/:splat"
  status = 200

# Soporte para Vue Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
